# -*- coding: utf-8 -*-
"""web_scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11DYLDtbTvYGQG1Li-WdhoROHffk9-ZC4
"""

from bs4 import BeautifulSoup
import requests

url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
soup = requests.get(url)
soup

soup = soup.text
soup

soup = BeautifulSoup(soup, "lxml")
soup

soup = soup.table
soup

tags = soup.find_all('tr')
tags

tags[0].text

data = []
for i in tags:
  data.append(i.text.split('\n')[1:-1])

data

output_data = [i for i in data if i[0]!=""]
print(output_data)

import csv
file = open('covid1.csv','w')
x = csv.writer(file)
for i in output_data:
  x.writerow(i)

import pandas as pd
df = pd.read_csv('covid1.csv')
df

country = list(df['Country,Other'])[0:50]
active_cases = list(df['ActiveCases'])[0:50]

new_active_cases = []
for i in active_cases:
  x = int(i.replace(',',''))
  new_active_cases.append(x)

import plotly.graph_objects as go
fig = go.Figure([go.Bar(x=country, y=new_active_cases)])
fig.show()

!pip install plotly==5.9.0

import plotly.graph_objects as go

fig = go.Figure(data=[go.Pie(labels=country, values=new_active_cases)])
fig.show()

